"""
Django settings for habit_tracker project.

Generated by 'django-admin startproject' using Django 5.2.4.
"""

from pathlib import Path
import dj_database_url
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Try to import env.py if it exists (for local development)
try:
    from . import env
    SECRET_KEY = env.SECRET_KEY
except ImportError:
    # For production - get from environment variables
    SECRET_KEY = os.environ.get('SECRET_KEY')
    if not SECRET_KEY:
        raise ValueError("SECRET_KEY environment variable must be set for production!")

DEBUG = os.environ.get('DEBUG', 'False').lower() in ('true', '1', 'yes')

# Heroku deployment fix: Get the app name dynamically
heroku_app_name = os.environ.get('HEROKU_APP_NAME')
if heroku_app_name:
    ALLOWED_HOSTS = [f'{heroku_app_name}.herokuapp.com', 'localhost', '127.0.0.1',
                     'power-of-change-tracker-3b5b0f9c1685.herokuapp.com',
                     'shellies-habit-tracker-640f97fbfff2.herokuapp.com']
else:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1',
                     'power-of-change-tracker-3b5b0f9c1685.herokuapp.com',
                     'shellies-habit-tracker-640f97fbfff2.herokuapp.com']

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crispy_forms',
    'crispy_bootstrap5',
    'habits',
]
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'habit_tracker.urls'python manage.py migrate
python manage.py createsuperuser
python manage.py create_default_categoriespython manage.py migrate
python manage.py createsuperuser
python manage.py create_default_categories

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'habit_tracker.wsgi.application'

# Database
# Default to sqlite for local development, use DATABASE_URL for production
if 'DATABASE_URL' in os.environ:
    DATABASES = {
        'default': dj_database_url.config(
            default=os.environ.get('DATABASE_URL'),
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.'
                'UserAttributeSimilarityValidator'
    },
    {
        'NAME': 'django.contrib.auth.password_validation.'
                'MinimumLengthValidator'
    },
    {
        'NAME': 'django.contrib.auth.password_validation.'
                'CommonPasswordValidator'
    },
    {
        'NAME': 'django.contrib.auth.password_validation.'
                'NumericPasswordValidator'
    },
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Use WhiteNoise for serving static files
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email settings for password reset
if DEBUG:
    # For development - prints emails to console
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    # For production - you may want to configure SMTP
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

DEFAULT_FROM_EMAIL = 'noreply@habittracker.com'

# Login/Logout redirect URLs
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'

# Security settings for production
if not DEBUG:
    # Enable essential security headers (these were incorrectly set to False)
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # Chrome-specific security settings
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = True  # Enable HTTPS redirect for production
    
    # Additional Chrome compatibility settings
    SECURE_REFERRER_POLICY = 'same-origin'
    SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin-allow-popups'
else:
    # Development settings - Chrome compatibility
    CSRF_COOKIE_SECURE = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SAMESITE = 'Lax'
    SESSION_COOKIE_SAMESITE = 'Lax'

# Enhanced CSRF protection for Chrome
CSRF_COOKIE_HTTPONLY = False  # Allow JavaScript access for AJAX requests
CSRF_USE_SESSIONS = False
CSRF_COOKIE_AGE = 31449600  # 1 year
CSRF_TRUSTED_ORIGINS = []

# Chrome-specific fixes
if 'HEROKU_APP_NAME' in os.environ:
    heroku_app_name = os.environ.get('HEROKU_APP_NAME')
    CSRF_TRUSTED_ORIGINS = [
        f'https://{heroku_app_name}.herokuapp.com',
        f'https://{heroku_app_name}.heroku.com',
        'https://power-of-change-tracker-3b5b0f9c1685.herokuapp.com',
        'https://shellies-habit-tracker-640f97fbfff2.herokuapp.com'
    ]
else:
    CSRF_TRUSTED_ORIGINS = [
        'https://power-of-change-tracker-3b5b0f9c1685.herokuapp.com',
        'https://shellies-habit-tracker-640f97fbfff2.herokuapp.com'
    ]

# Session settings for better Chrome compatibility
SESSION_COOKIE_AGE = 1209600  # 2 weeks
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_COOKIE_NAME = 'habit_tracker_sessionid'

# Additional Chrome compatibility headers
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    USE_TZ = True

