# Generated by Django 5.2.4 on 2025-08-01 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
